# Generated by Django 5.2.8 on 2026-01-01 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_for', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=50)),
                ('appointment_date', models.DateTimeField()),
                ('appointment_status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'APPOINTMENT_TABLE',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=10)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'AREA_TABLE',
            },
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('deliveryboy_id', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryboy_name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('is_available', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'DELIVERY_BOY_TABLE',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=15)),
                ('qty', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('cover_img_path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PRODUCT_TABLE',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PRODUCT_CATEGORY_TABLE',
            },
        ),
        migrations.CreateModel(
            name='AppointmentPayment',
            fields=[
                ('app_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(max_length=6)),
                ('amount', models.IntegerField()),
                ('payment_status', models.IntegerField(default=0)),
                ('payment_token', models.CharField(max_length=50)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_time', models.TimeField(auto_now_add=True)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.appointment')),
            ],
            options={
                'db_table': 'APPOINTMENT_PAYMENT_TABLE',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('is_admin', models.IntegerField(default=0)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.area')),
            ],
            options={
                'db_table': 'CUSTOMER_TABLE',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.customer'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.IntegerField(default=0)),
                ('delivery_date', models.DateField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.area')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.customer')),
                ('deliveryboy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.deliveryboy')),
            ],
            options={
                'db_table': 'ORDER_TABLE',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('ord_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(max_length=6)),
                ('amount', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('payment_token', models.CharField(max_length=50)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_time', models.TimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.order')),
            ],
            options={
                'db_table': 'ORDER_PAYMENT_TABLE',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.order')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.product')),
            ],
            options={
                'db_table': 'ORDER_DETAIL_TABLE',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=100)),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.product')),
            ],
            options={
                'db_table': 'GALLERY_TABLE',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.customer')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.product')),
            ],
            options={
                'db_table': 'CART_TABLE',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.productcategory'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.area')),
            ],
            options={
                'db_table': 'VENDOR_TABLE',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.vendor'),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.vendor'),
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('vet_id', models.AutoField(primary_key=True, serialize=False)),
                ('vet_name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('vet_profile', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('documents', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('charges', models.IntegerField()),
                ('availability_status', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.area')),
            ],
            options={
                'db_table': 'VET_TABLE',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.customer')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.product')),
                ('vet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.vet')),
            ],
            options={
                'db_table': 'FEEDBACK_TABLE',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='vet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.vet'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('whislist_id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.customer')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.product')),
            ],
            options={
                'db_table': 'WHISLIST_TABLE',
            },
        ),
    ]
