# Generated by Django 5.2.8 on 2026-01-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='appointmentpayment',
            name='payment_token',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='deliveryboy_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='email',
            field=models.EmailField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_img_path',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='vet',
            name='email',
            field=models.EmailField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vet',
            name='vet_name',
            field=models.CharField(max_length=35),
        ),
    ]
