# Generated by Django 5.2.8 on 2026-01-05 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_alter_appointment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='prod_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test2.product'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='vet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test2.vet'),
        ),
    ]
