# Generated by Django 5.2.8 on 2026-01-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0003_alter_feedback_prod_id_alter_feedback_vet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='otp_used',
            field=models.IntegerField(default=0),
        ),
    ]
