# Generated by Django 5.2.8 on 2026-01-17 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0004_customer_otp_customer_otp_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_profile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='deliveryboy_profile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_profile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentpayment',
            name='payment_token',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='deliveryboy_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='prod_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test2.product'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='vet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test2.vet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_img_path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vet',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vet',
            name='vet_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vet',
            name='vet_profile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
