# Generated by Django 5.2.7 on 2026-01-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0005_customer_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='vet',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
