# Generated by Django 5.2.7 on 2026-01-26 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0006_alter_customer_password_alter_deliveryboy_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces.', regex='^[a-zA-Z\\s]*$')]),
        ),
    ]
