# Generated by Django 5.2.7 on 2026-01-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0007_alter_customer_contact_alter_customer_cust_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='deliveryboy_profile',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_boys/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_img_path',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_profile',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='vet_profile',
            field=models.ImageField(blank=True, null=True, upload_to='vets/'),
        ),
    ]
