# Generated by Django 5.2.7 on 2026-01-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0008_alter_customer_user_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='specialization',
            field=models.CharField(choices=[('Dog Specialist', 'Dog Specialist'), ('Cat Specialist', 'Cat Specialist'), ('General (Both)', 'General (Both Dog & Cat)')], default='General (Both)', max_length=50),
        ),
    ]
