# Generated by Django 5.2.7 on 2026-01-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0009_vet_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='specialization',
            field=models.CharField(choices=[('Dog Specialist', 'Dog Specialist'), ('Cat Specialist', 'Cat Specialist'), ('General (Both)', 'General (Both Dog & Cat)')], default='General (Both)', max_length=20),
        ),
    ]
