# Generated by Django 5.2.7 on 2026-01-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0010_alter_vet_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='deliveryboy_profile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_img_path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_profile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='vet_profile',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
