# Generated by Django 5.2.7 on 2026-01-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0011_alter_deliveryboy_deliveryboy_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='documents',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
