# Generated by Django 5.2.7 on 2026-01-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0012_alter_vet_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='documents',
            field=models.CharField(max_length=100),
        ),
    ]
