# Generated by Django 5.2.8 on 2026-01-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0013_alter_vet_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='vet_docs/'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='vet_profile',
            field=models.ImageField(blank=True, null=True, upload_to='vet_profiles/'),
        ),
    ]
