# Generated by Django 5.2.8 on 2026-02-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0014_alter_vet_documents_alter_vet_vet_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='otp_used',
            field=models.IntegerField(default=0),
        ),
    ]
