# Generated by Django 5.2.8 on 2026-02-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0015_vet_otp_vet_otp_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
