# Generated by Django 5.2.8 on 2026-02-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0016_vet_close_time_vet_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='last_timing_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
