# Generated by Django 5.2.8 on 2026-02-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0017_vet_last_timing_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_timer_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_cash_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='strike_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vet',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='VetSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('vet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.vet')),
            ],
            options={
                'db_table': 'VET_SCHEDULE_TABLE',
            },
        ),
    ]
