# Generated by Django 5.2.7 on 2026-02-21 04:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0018_appointment_medical_report_appointment_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='appointment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test2.appointment'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='vet',
            name='vet_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces.', regex='^[a-zA-Z\\s]*$')]),
        ),
    ]
