# Generated by Django 5.2.7 on 2026-02-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0019_feedback_appointment_id_alter_vet_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='cancel_count',
            field=models.IntegerField(default=0),
        ),
    ]
