# Generated by Django 5.2.8 on 2026-03-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0020_vet_cancel_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profiles/'),
        ),
    ]
