# Generated by Django 5.2.7 on 2026-03-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0021_alter_customer_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
