# Generated by Django 5.2.8 on 2026-03-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0022_appointment_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='deliveryboy_profile',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_profiles/'),
        ),
    ]
