# Generated by Django 5.2.7 on 2026-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0023_alter_deliveryboy_deliveryboy_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='charges',
            field=models.IntegerField(default=0),
        ),
    ]
