# Generated by Django 5.2.8 on 2026-03-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0024_appointment_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_profile',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_profiles/'),
        ),
    ]
