# Generated by Django 5.2.8 on 2026-03-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0025_vendor_status_alter_vendor_vendor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_path',
            field=models.ImageField(upload_to='product_gallery/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_img_path',
            field=models.ImageField(upload_to='product_covers/'),
        ),
    ]
