# Generated by Django 5.2.7 on 2026-03-20 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0026_alter_gallery_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='area_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test2.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='reschedule_status',
            field=models.IntegerField(default=0),
        ),
    ]
