# Generated by Django 5.2.7 on 2026-03-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0027_deliveryboy_area_id_deliveryboy_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='is_available',
            field=models.IntegerField(default=0),
        ),
    ]
