# Generated by Django 5.2.7 on 2026-03-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0028_alter_deliveryboy_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='is_available',
            field=models.IntegerField(default=1),
        ),
    ]
