# Generated by Django 5.2.7 on 2026-03-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0030_alter_deliveryboy_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
