# Generated by Django 5.2.7 on 2026-03-21 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0031_remove_deliveryboy_is_approved_deliveryboy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test2.vendor'),
            preserve_default=False,
        ),
    ]
