# Generated by Django 5.2.7 on 2026-03-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0032_order_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='vendor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test2.vendor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryboy_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test2.deliveryboy'),
        ),
    ]
