# Generated by Django 5.2.7 on 2026-03-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0033_remove_order_vendor_id_orderdetail_vendor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='detail_status',
            field=models.IntegerField(default=0),
        ),
    ]
