# Generated by Django 5.2.7 on 2026-03-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0034_orderdetail_detail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
