# Generated by Django 5.2.7 on 2026-03-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0035_order_cancelled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
