# Generated by Django 5.2.7 on 2026-03-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0036_remove_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='order_detail_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test2.orderdetail'),
        ),
    ]
