# Generated by Django 5.2.8 on 2026-03-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0036_remove_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='otp_used',
            field=models.IntegerField(default=0),
        ),
    ]
