# Generated by Django 5.2.8 on 2026-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0037_deliveryboy_otp_deliveryboy_otp_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
