# Generated by Django 5.2.8 on 2026-03-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0038_alter_deliveryboy_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
