# Generated by Django 5.2.8 on 2026-03-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0039_alter_customer_otp_alter_vet_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='otp_used',
            field=models.IntegerField(default=0),
        ),
    ]
