# Generated by Django 5.2.7 on 2026-03-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0037_feedback_order_detail_id'),
        ('test2', '0040_vendor_otp_vendor_otp_used'),
    ]

    operations = [
    ]
