# Generated by Django 5.2.7 on 2026-04-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0041_merge_20260328_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetschedule',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
