# Generated by Django 5.2.7 on 2026-04-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0042_vetschedule_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
