# Generated by Django 5.2.8 on 2026-04-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0043_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(max_length=60),
        ),
    ]
