# Generated by Django 5.2.7 on 2026-04-14 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0044_alter_product_prod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='appointment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test2.appointment'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='prod_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test2.product'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='vet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test2.vet'),
        ),
    ]
