# Generated by Django 5.2.7 on 2026-08-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0045_alter_feedback_appointment_id_alter_feedback_prod_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment_reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
