# Generated by Django 5.2.7 on 2026-08-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0046_feedback_sentiment_feedback_sentiment_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='sentiment_reason',
        ),
    ]
